Algoritmo "crescente"

Var

x,y, valor : inteiro

Inicio

   escreval("Digite dois numeros: ")
   escreva("Primeiro: ")
   leia(x)
   escreva("Segundo: ")
   leia(y)

   enquanto x <> y faca
   se x < y entao
    escreval("Crescente")
      senao
        escreval ("Decrescente")
        fimse
        
          escreval ("Digite outros dois numeros: ")
          leia(x)
          leia(y)
        
      fimenquanto
        

Fimalgoritmo