Algoritmo "Media_Ponderada"



Var

x, i : inteiro
media, a, b, c : real

Inicio

    escreva("Quantos casos voce vai digitar ? : ")
    leia(x)
    
       para i de 1 ate x faca
         escreval("Digite tres numeros: ")
         leia(a)
         leia(b)
         leia(c)
         media <- (a * 2 + b * 3 + c * 5)/10
         escreval("MEDIA = ",media:3:1)
         
         
         
         
       fimpara

Fimalgoritmo