Algoritmo "senha_escolha(Sozinho)"



Var

x, senha  : inteiro

Inicio

  escreva("Escolha uma senha: ")
  leia (senha)

    escreva("Para acessar, digite a senha: ")

    enquanto senha <> x faca
      leia (x)
        se senha = x entao
          escreva("Acesso Autorizado")
            senao
              escreval("Acesso Negado, tente novamente")
          fimse
      fimenquanto





Fimalgoritmo